# Setup
title:               NSU Programming
tagline:             'Программирование на C++ и Python'
description:         'Сайт курса "Программирование на C++ и Python" для студентов ФФ НГУ.'
url:                 http://nsu-programming.github.io
baseurl:             ''
repo:                https://github.com/NSU-Programming/NSU-Programming.github.io

# About/contact
author:
  email:             vit.vorobiev@gmail.com

# Gems
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
