theme: jekyll-theme-cayman
title: Программирование на C++ и python

email: vit.vorobiev@gmail.com
description: "" # >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
