# Setup
title:               'NSU Programming'
tagline:             'Программирование на C++ и Python'
description:         'Сайт курса "Программирование на C++ и Python" для студентов ФФ НГУ.'
url:                 ''
baseurl:             ''
repo:                'https://github.com/NSU-Programming/NSU-Programming.github.io'
google_analytics_id: 'UA-21390409-2'

# About/contact
author:
  email:             vit.vorobiev@gmail.com

# Gems
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
